---
title: "Exploratory Data Analysis"
author: "JJC"
format: 
    html:
        toc: true
        toc-depth: 2
        toc-title: Table of contents
        # number-sections: true
        code-fold: true
        highlight-style: github
editor: visual
---

## Mortality Rates

```{r}
#| include: false
#| label: load_libraries

library(data.table)
library(kableExtra)
library(ggplot2)
library(plotly)
library(janitor)
library(tidyr)
```

### Mortality rate by age category

Calculate mortality rates per 10,000 persons for each age category

```{r}
#| include: false
#| 

scot_dt <- readRDS(file = "./data-clean/scot_dt.rds")
scot_dt[, rate := mort/pop * 10000]

setcolorder(scot_dt, c("year", "age_cat", "mort", "pop", "rate"))
```

### Mortality rate compared to baseline

The baseline level is the 2019 numbers for each age group.

```{r}

library(purrr)
# Set the base rate from year 2019 values
base <- scot_dt[year==2019, rate]
# y <- 2019
# adj_rate <- scot_dt[year==eval(y), rate] - base

calc_adj_rate <- function(yr){
    scot_dt[year==eval(yr), rate] - base
}

adj <- map(2010:2022, calc_adj_rate) 
adj <- unlist(adj)
scot_dt[, rate_adj := adj]
head(scot_dt, 10) |> 
    kable()
```

## Trend Lines

### Older

```{r}
#| warning: false

older <- scot_dt[age_cat  %in% c("65-74", "75-84", "85+")]

# Visualize changes over time
ggplot(older, aes(x = year, y = rate_adj)) +
  geom_line(aes(group = age_cat), color = "grey50") +
  geom_point(aes(color = age_cat, shape = age_cat)) +
  # x-axis breaks for years from 2010 to 2022
  scale_x_continuous(breaks = 2010:2022) 
```

### Middle Ages

```{r}

working <- scot_dt[age_cat %in% c("15-44", "45-64"), ]
ggplot(working, aes(x = year, y = rate_adj)) +
  geom_line(aes(group = age_cat), color = "grey50") +
  geom_point(aes(color = age_cat, shape = age_cat)) +
  # x-axis breaks for years from 2010 to 2022
  scale_x_continuous(breaks = 2010:2022) 

```

### Young

```{r}

young <- scot_dt[age_cat %in% c("0", "1-14")]

ggplot(young, aes(x = year, y = rate_adj)) +
  geom_line(aes(group = age_cat), color = "grey50") +
  geom_point(aes(color = age_cat, shape = age_cat)) +
  # x-axis breaks for years from 2010 to 2022
  scale_x_continuous(breaks = 2010:2022) 
```
